export { default as Layout } from './Layout/layout'
export { default as Header } from './Header/header'
export { default as Bio } from './bio'
export { default as Skills } from './Skills/skills'
export { default as Image } from './image'
export { default as SEO } from './seo'
export { default as SocialMedia } from './SocialMedia/socialMedia'
export { default as Resume } from './Resume/resume'

export { Navigation } from './Navigation'