export { default as Header } from './header/header'
export { default as Layout } from './layout/layout'
export { default as Bio } from './bio/bio'
export { default as Skills } from './skills'
export { default as Image } from './image'
export { default as SEO } from './seo'