export { default as Header } from './header/Header'
export { default as Layout } from './layout/layout'
export { default as Bio } from './bio/Bio'
export { default as Skills } from './Skills'
export { default as Image } from './Image'
export { default as SEO } from './seo'